######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 10 11:26:27 2012
######################################################################

TEMPLATE = lib
CONFIG  += plugin
TARGET = 
DESTDIR = ../../../bin/
OBJECTS_DIR = ./debug
DEPENDPATH += .
INCLUDEPATH += . ../../interfaces/core/ ../../interfaces/modules/

# Input
HEADERS += rtx.h
SOURCES += rtx.cpp
