######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 10 11:26:27 2012
######################################################################

TEMPLATE = lib
CONFIG  += plugin
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../core/include/ ../../interfaces/environment/ ../../core/ ../../interfaces/hardware/

# Input
HEADERS += rtx.h
SOURCES += rtx.cpp
