######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 18 14:55:12 2012
######################################################################

TEMPLATE = lib
CONFIG  += plugin
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../core/include/ ../../interfaces/environment/ ../../core/

# Input
HEADERS += temperature.h
SOURCES += temperature.cpp
