######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 18 14:46:55 2012
######################################################################


TEMPLATE = lib
CONFIG  += plugin
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../core/include/ ../../interfaces/environment/ ../../core/ ../../interfaces/hardware/

# Input
HEADERS += sensor.h
SOURCES += sensor.cpp
