######################################################################
# Automatically generated by qmake (2.01a) Fri May 18 12:25:50 2012
######################################################################

TEMPLATE = lib
CONFIG  += plugin
TARGET = 
DESTDIR = ../../../bin/modules/
OBJECTS_DIR = ./debug
DEPENDPATH += .
INCLUDEPATH += . ../../interfaces/core/ ../../interfaces/modules/

# Input
HEADERS += nodePHY.h
SOURCES += nodePHY.cpp
