######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 5 13:03:18 2012
######################################################################

TEMPLATE = lib
CONFIG  += plugin
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../core/include/ ../../interfaces/environment/ ../../core/

# Input
HEADERS += scene.h
SOURCES += scene.cpp
