######################################################################
# Automatically generated by qmake (2.01a) Fri May 18 01:21:52 2012
######################################################################

TEMPLATE = lib
CONFIG  += plugin
TARGET = 
DESTDIR = ../../../bin/modules/
OBJECTS_DIR = ./debug
DEPENDPATH += .
INCLUDEPATH += . ../../interfaces/core/ ../../interfaces/modules/

# Input
HEADERS += csma_ca.h
SOURCES += csma_ca.cpp
