######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 10 12:34:23 2012
######################################################################

TEMPLATE = lib
CONFIG  += plugin
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../interfaces/core/ ../../interfaces/modules/

# Input
HEADERS += radioChannel.h
SOURCES += radioChannel.cpp
