######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 10 12:34:23 2012
######################################################################

TEMPLATE = lib
CONFIG  += plugin
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../core/include/ ../../interfaces/environment/ ../../core/ ../../interfaces/hardware/

# Input
HEADERS += radioChannel.h
SOURCES += radioChannel.cpp
